apiVersion: batch/v1
kind: Job
metadata:
  name: podrecycler
spec:
  template:
    metadata:
      labels:
        app: podrecycler
    spec:
      containers:
      - name: podrecycler-container
        image: machgo/podrecycler
      serviceAccountName: robot
      restartPolicy: Never

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: robot
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: robot-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: pod-and-pod-logs-reader
subjects:
- kind: ServiceAccount
  name: robot
  namespace: default
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pod-and-pod-logs-reader
rules:
- apiGroups: [""]
  resources: ["pods", "pods/log"]
  verbs: ["get", "list", "delete"]
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: testerpod
spec:
  replicas: 4
  template:
    metadata:
      labels:
        podrecycler: "yes"
    spec:
      containers:
      - name: nginx
        image: nginx
